# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Card": "00_card.ipynb"}

modules = ["card.py"]

doc_url = "https://plablo09.github.io/ejemplo_nbdev/"

git_url = "https://github.com/plablo09/ejemplo_nbdev/tree/main/"

def custom_doc_links(name): return None
